cgabackup-mysql: BREAKING CHANGE! don't pass password per cmdline to mysql
- new config file format
- need to install 'crudini'

diff --git a/client/cgabackup-mysql b/client/cgabackup-mysql
--- a/client/cgabackup-mysql
+++ b/client/cgabackup-mysql
@@ -13,12 +13,35 @@
 # To set the correct rights use:
 # grant select on *.* to cgabackup@localhost identified by 'PASSWORD';
 
-. /etc/cgabackup-mysql.conf
-DBs=`mysql -u$USER -p$PASSWORD -B -N -e "show databases;"`
+CFGFILE="/etc/cgabackup-mysql.conf"
+
+BACKUP_PATH=`crudini --get ${CFGFILE} cgabackup backup_path`
+ERR=$?
+if [ $ERR == 127 ] ; then
+  echo "An error occured. Maybe you need to install 'crudini'?"
+  exit 1
+elif [ $ERR != 0 ] ; then
+  echo "An error occured. Maybe you need to update ${CFGFILE}?"
+  echo
+  echo "Example config file:"
+  echo "https://github.com/plepe/CGA-Backup/blob/master/client/cgabackup-mysql.conf"
+  exit 1
+fi
+
+if [ ! -d $BACKUP_PATH ] ; then
+  echo "Backup path '$BACKUP_PATH' does not exist. Please create!"
+  exit 1
+fi
+
+DBs=`mysql --defaults-extra-file=${CFGFILE} -B -N -e "show databases;"`
+if [ $? != 0 ] ; then
+  echo "An error occured. Can't get list of databases."
+  exit 1
+fi
 
 for DB in $DBs ; do
 	echo -n "Backup of DB $DB - "
-	mysqldump -u$USER -p$PASSWORD --skip-lock-tables --skip-comments $DB > $BACKUP_PATH/__$DB.sql
+	mysqldump --defaults-extra-file=${CFGFILE} --skip-lock-tables --skip-comments $DB > $BACKUP_PATH/__$DB.sql
 
         if [ ! -f $BACKUP_PATH/$DB.sql ] ; then
 		mv $BACKUP_PATH/__$DB.sql $BACKUP_PATH/$DB.sql
